services:
  - type: worker
    name: tournament-draft-bot
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: starter  # Обязательно меняем free на starter, иначе будет старая ошибка
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: DATA_DIR
        value: /app/data
    disk:
      name: tournament-data
      mountPath: /app/data
      sizeGB: 1