"""Initialize mini-games in the database."""

from storage.db import get_pool
from storage.minigame_store import minigame_store


async def initialize_minigames() -> None:
    """Initialize all mini-games in the database."""
    pool = await get_pool()
    async with pool.acquire() as conn:
        # Games on luck (Priority 1)
        games = [
            # 1. Rock-Paper-Scissors
            {
                "id": "rps",
                "command_name": "rps",
                "name": "Камень-Ножницы-Бумага",
                "description": "Классическая игра. Камень бьёт ножницы, ножницы бьют бумагу, бумага бьёт камень.",
                "category": "luck",
                "difficulty": "easy",
                "min_bet": 10,
                "max_bet": 1000,
                "multiplier": 2.0,
                "is_pvp": True,
                "is_pve": True,
            },
            # 2. Guess Number
            {
                "id": "guess_number",
                "command_name": "guess_number",
                "name": "Угадай число",
                "description": "Бот загадывает число от 1 до 100. У вас есть 7 попыток.",
                "category": "luck",
                "difficulty": "easy",
                "min_bet": 20,
                "max_bet": 500,
                "multiplier": 5.0,
                "is_pvp": False,
                "is_pve": True,
            },
            # 3. Coin Flip
            {
                "id": "coin_flip",
                "command_name": "coin_flip",
                "name": "Монетка",
                "description": "Орел или решка. Кто угадал тот и выиграл.",
                "category": "luck",
                "difficulty": "easy",
                "min_bet": 10,
                "max_bet": 1000,
                "multiplier": 2.0,
                "is_pvp": True,
                "is_pve": True,
            },
            # 4. Dice Roll
            {
                "id": "dice_roll",
                "command_name": "dice_roll",
                "name": "Кубик",
                "description": "Бросьте кубик. У кого больше выпадет тот и победил.",
                "category": "luck",
                "difficulty": "easy",
                "min_bet": 10,
                "max_bet": 1000,
                "multiplier": 2.0,
                "is_pvp": True,
                "is_pve": True,
            },
            # 5. Guess Emoji
            {
                "id": "guess_emoji",
                "command_name": "guess_emoji",
                "name": "Угадай эмодзи",
                "description": "Бот показывает скрытый эмодзи с подсказками.",
                "category": "luck",
                "difficulty": "medium",
                "min_bet": 15,
                "max_bet": 300,
                "multiplier": 3.0,
                "is_pvp": False,
                "is_pve": True,
            },
            # 6. Wheel of Fortune
            {
                "id": "wheel",
                "command_name": "wheel",
                "name": "Колесо фортуны",
                "description": "Крутите колесо с разными множителями.",
                "category": "luck",
                "difficulty": "medium",
                "min_bet": 20,
                "max_bet": 500,
                "multiplier": 5.0,
                "is_pvp": False,
                "is_pve": True,
            },
            # 7. Guess Color
            {
                "id": "guess_color",
                "command_name": "guess_color",
                "name": "Угадай цвет",
                "description": "Бот загадывает один из 3 цветов.",
                "category": "luck",
                "difficulty": "easy",
                "min_bet": 10,
                "max_bet": 200,
                "multiplier": 3.0,
                "is_pvp": False,
                "is_pve": True,
            },
            # 8. Tic-Tac-Toe
            {
                "id": "tictactoe",
                "command_name": "tictactoe",
                "name": "Крестики-Нолики",
                "description": "Классическая игра 3x3. Кто первый соберёт 3 в ряд - победитель.",
                "category": "luck",
                "difficulty": "medium",
                "min_bet": 20,
                "max_bet": 500,
                "multiplier": 2.0,
                "is_pvp": True,
                "is_pve": True,
            },
            # 9. Reflex Test
            {
                "id": "reflex_test",
                "command_name": "reflex_test",
                "name": "Быстрый тест",
                "description": "Нажмите кнопку как можно быстрее при появлении эмодзи.",
                "category": "luck",
                "difficulty": "easy",
                "min_bet": 10,
                "max_bet": 200,
                "multiplier": 2.0,
                "is_pvp": False,
                "is_pve": True,
            },
            # 10. Spin Bottle
            {
                "id": "spin_bottle",
                "command_name": "spin_bottle",
                "name": "Бутылочка",
                "description": "Крутите бутылочку. На кого она укажет - тот выполняет вызов.",
                "category": "luck",
                "difficulty": "medium",
                "min_bet": 25,
                "max_bet": 500,
                "multiplier": 2.0,
                "is_pvp": True,
                "is_pve": False,
            },
            # Quiz games (Priority 2)
            # 11. Math Quiz
            {
                "id": "math_quiz",
                "command_name": "math_quiz",
                "name": "Математическая викторина",
                "description": "Решите математический пример за 30 секунд.",
                "category": "quiz",
                "difficulty": "medium",
                "min_bet": 25,
                "max_bet": 500,
                "multiplier": 2.0,
                "is_pvp": False,
                "is_pve": True,
            },
            # 12. Word Guess
            {
                "id": "word_guess",
                "command_name": "word_guess",
                "name": "Угадай слово",
                "description": "Угадайте слово из 5 букв по подсказкам.",
                "category": "quiz",
                "difficulty": "medium",
                "min_bet": 20,
                "max_bet": 400,
                "multiplier": 4.0,
                "is_pvp": False,
                "is_pve": True,
            },
            # 13. Riddles
            {
                "id": "riddles",
                "command_name": "riddles",
                "name": "Загадки",
                "description": "Отгадайте загадку с 3 попытками и подсказками.",
                "category": "quiz",
                "difficulty": "medium",
                "min_bet": 15,
                "max_bet": 300,
                "multiplier": 3.0,
                "is_pvp": False,
                "is_pve": True,
            },
            # 14. Word Chain
            {
                "id": "word_chain",
                "command_name": "word_chain",
                "name": "Словесные цепочки",
                "description": "Называйте слова на заданную букву по очереди.",
                "category": "quiz",
                "difficulty": "medium",
                "min_bet": 20,
                "max_bet": 400,
                "multiplier": 2.0,
                "is_pvp": True,
                "is_pve": False,
            },
            # 15. Millionaire
            {
                "id": "millionaire",
                "command_name": "millionaire",
                "name": "Кто хочет стать миллионером",
                "description": "Ответьте на 10 вопросов с подсказками.",
                "category": "quiz",
                "difficulty": "hard",
                "min_bet": 50,
                "max_bet": 1000,
                "multiplier": 10.0,
                "is_pvp": False,
                "is_pve": True,
            },
            # 16. Hangman
            {
                "id": "hangman",
                "command_name": "hangman",
                "name": "Виселица",
                "description": "Классическая виселица. Угадайте слово по буквам.",
                "category": "quiz",
                "difficulty": "medium",
                "min_bet": 15,
                "max_bet": 300,
                "multiplier": 2.0,
                "is_pvp": False,
                "is_pve": True,
            },
            # 17. Trivia
            {
                "id": "trivia",
                "command_name": "trivia",
                "name": "Тест на эрудицию",
                "description": "10 вопросов из разных категорий. 7 правильных = победа.",
                "category": "quiz",
                "difficulty": "hard",
                "min_bet": 30,
                "max_bet": 600,
                "multiplier": 5.0,
                "is_pvp": False,
                "is_pve": True,
            },
            # 18. Memory
            {
                "id": "memory",
                "command_name": "memory",
                "name": "Память",
                "description": "Запомните последовательность эмодзи и повторите её.",
                "category": "quiz",
                "difficulty": "medium",
                "min_bet": 15,
                "max_bet": 300,
                "multiplier": 2.0,
                "is_pvp": False,
                "is_pve": True,
            },
            # 19. Logic Puzzle
            {
                "id": "logic_puzzle",
                "command_name": "logic_puzzle",
                "name": "Логические задачи",
                "description": "Решите логическую задачу с 3 попытками.",
                "category": "quiz",
                "difficulty": "hard",
                "min_bet": 25,
                "max_bet": 500,
                "multiplier": 4.0,
                "is_pvp": False,
                "is_pve": True,
            },
            # 20. Anagrams
            {
                "id": "anagrams",
                "command_name": "anagrams",
                "name": "Анаграммы",
                "description": "Соберите слово из перемешанных букв.",
                "category": "quiz",
                "difficulty": "medium",
                "min_bet": 15,
                "max_bet": 300,
                "multiplier": 3.0,
                "is_pvp": False,
                "is_pve": True,
            },
            # Casino games (Priority 3)
            # 21. Roulette
            {
                "id": "roulette",
                "command_name": "roulette",
                "name": "Рулетка",
                "description": "Классическая рулетка. Ставьте на цвет, чёт/нечёт или число.",
                "category": "casino",
                "difficulty": "medium",
                "min_bet": 50,
                "max_bet": 2000,
                "multiplier": 35.0,
                "is_pvp": False,
                "is_pve": True,
            },
            # 22. Blackjack
            {
                "id": "blackjack",
                "command_name": "blackjack",
                "name": "Блэкджек",
                "description": "Классический блэкджек. Наберите 21 или больше чем дилер.",
                "category": "casino",
                "difficulty": "medium",
                "min_bet": 50,
                "max_bet": 2000,
                "multiplier": 3.0,
                "is_pvp": False,
                "is_pve": True,
            },
            # 23. Slots
            {
                "id": "slots",
                "command_name": "slots",
                "name": "Слоты",
                "description": "Однорукий бандит. 3 барабана с символами.",
                "category": "casino",
                "difficulty": "easy",
                "min_bet": 20,
                "max_bet": 1000,
                "multiplier": 10.0,
                "is_pvp": False,
                "is_pve": True,
            },
            # 24. Craps
            {
                "id": "craps",
                "command_name": "craps",
                "name": "Крэпс",
                "description": "Бросьте 2 кубика. Ставьте на Pass Line или Don't Pass.",
                "category": "casino",
                "difficulty": "hard",
                "min_bet": 50,
                "max_bet": 2000,
                "multiplier": 2.0,
                "is_pvp": False,
                "is_pve": True,
            },
            # 25. Poker
            {
                "id": "poker",
                "command_name": "poker",
                "name": "Покер",
                "description": "Упрощённый покер. Лучшее комбо из 5 карт выигрывает.",
                "category": "casino",
                "difficulty": "hard",
                "min_bet": 100,
                "max_bet": 5000,
                "multiplier": 2.0,
                "is_pvp": False,
                "is_pve": True,
            },
            # 26. Baccarat
            {
                "id": "baccarat",
                "command_name": "baccarat",
                "name": "Баккара",
                "description": "Простая карточная игра. Ставьте на Player или Banker.",
                "category": "casino",
                "difficulty": "easy",
                "min_bet": 50,
                "max_bet": 2000,
                "multiplier": 2.0,
                "is_pvp": False,
                "is_pve": True,
            },
            # 27. Lottery
            {
                "id": "lottery",
                "command_name": "lottery",
                "name": "Лотерея",
                "description": "Купите билет. Совпали числа - победа!",
                "category": "casino",
                "difficulty": "easy",
                "min_bet": 10,
                "max_bet": 100,
                "multiplier": 100.0,
                "is_pvp": False,
                "is_pve": True,
            },
            # 28. Snap
            {
                "id": "snap",
                "command_name": "snap",
                "name": "Snap",
                "description": "Сравните карты с дилером. У кого больше очков - победа.",
                "category": "casino",
                "difficulty": "medium",
                "min_bet": 30,
                "max_bet": 1000,
                "multiplier": 2.0,
                "is_pvp": False,
                "is_pve": True,
            },
            # 29. Dicebet
            {
                "id": "dicebet",
                "command_name": "dicebet",
                "name": "Dicebet",
                "description": "Бросьте 2 кубика. Угадайте сумму.",
                "category": "casino",
                "difficulty": "medium",
                "min_bet": 20,
                "max_bet": 500,
                "multiplier": 6.0,
                "is_pvp": False,
                "is_pve": True,
            },
            # 30. High-Low
            {
                "id": "highlow",
                "command_name": "highlow",
                "name": "High-Low",
                "description": "Угадайте, будет следующая карта выше или ниже.",
                "category": "casino",
                "difficulty": "easy",
                "min_bet": 20,
                "max_bet": 500,
                "multiplier": 2.0,
                "is_pvp": False,
                "is_pve": True,
            },
            # Mixed games (Priority 5)
            # 31. Triple Chance
            {
                "id": "triple_chance",
                "command_name": "triple_chance",
                "name": "Тройной шанс",
                "description": "Угадайте число от 1 до 3. Шанс победы 33.3%.",
                "category": "mixed",
                "difficulty": "easy",
                "min_bet": 10,
                "max_bet": 200,
                "multiplier": 3.0,
                "is_pvp": False,
                "is_pve": True,
            },
            # 32. Sequence Memory
            {
                "id": "sequence_memory",
                "command_name": "sequence_memory",
                "name": "Вспомни последовательность",
                "description": "Запомните последовательность эмодзи и повторите её.",
                "category": "mixed",
                "difficulty": "medium",
                "min_bet": 15,
                "max_bet": 300,
                "multiplier": 2.0,
                "is_pvp": False,
                "is_pve": True,
            },
            # 33. Flag Quiz
            {
                "id": "flag_quiz",
                "command_name": "flag_quiz",
                "name": "Угадай флаг",
                "description": "Угадайте страну по флагу.",
                "category": "mixed",
                "difficulty": "medium",
                "min_bet": 20,
                "max_bet": 400,
                "multiplier": 3.0,
                "is_pvp": False,
                "is_pve": True,
            },
        ]

        for game in games:
            await conn.execute(
                """
                INSERT INTO minigames (id, command_name, name, description, category, difficulty, min_bet, max_bet, multiplier, is_pvp, is_pve, is_active)
                VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, TRUE)
                ON CONFLICT (id) DO UPDATE SET
                    command_name = EXCLUDED.command_name,
                    name = EXCLUDED.name,
                    description = EXCLUDED.description,
                    category = EXCLUDED.category,
                    difficulty = EXCLUDED.difficulty,
                    min_bet = EXCLUDED.min_bet,
                    max_bet = EXCLUDED.max_bet,
                    multiplier = EXCLUDED.multiplier,
                    is_pvp = EXCLUDED.is_pvp,
                    is_pve = EXCLUDED.is_pve,
                    is_active = TRUE
                """,
                game["id"],
                game.get("command_name", game["id"]),
                game["name"],
                game["description"],
                game["category"],
                game["difficulty"],
                game["min_bet"],
                game["max_bet"],
                game["multiplier"],
                game["is_pvp"],
                game["is_pve"],
            )
